# Site settings
title: Moeen Mostafavi
academic_email: moeen@virginia.edu

description: > # this means to ignore newlines until "baseurl:"
  Computational social scientist and data scientist working on NLP, machine learning, and decision support; now at VRS applying statistical modeling to mortgage-backed securities.

#baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://moeenm.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: moeenm
linkedin_username: moeenmostafavi
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
